# site settings
title: Sandeep Jaiswal
subtitle: Software Developer
email: sandeepjswl123@gmail.com
description: I'm a Software Developer, You can checkout my projects here
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: Mahadevpura, Whitefield
city: Bangalore
state: Karnataka
zip_code: 560048
country: India
phone: +91-7584033349

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/sandyjswl
instagram_url: 
linkedin_url: https://www.linkedin.com/in/sandyjswl/
pinterest_url:
slack_url:
twitter_url: 
gmail_url:  

# build settings
markdown: kramdown

sass:
  style: compressed
